# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfs.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x03\x64\x66s\"3\n\x11StoreBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"Z\n\x12StoreBlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\"\n\nerror_code\x18\x02 \x01(\x0e\x32\x0e.dfs.ErrorCode\x12\x0f\n\x07message\x18\x03 \x01(\t\"(\n\x14RetrieveBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"k\n\x15RetrieveBlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\"\n\nerror_code\x18\x03 \x01(\x0e\x32\x0e.dfs.ErrorCode\x12\x0f\n\x07message\x18\x04 \x01(\t*6\n\tErrorCode\x12\x08\n\x04NONE\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x10\n\x0cINVALID_DATA\x10\x02\x32\x91\x01\n\x08\x44\x61taNode\x12=\n\nStoreBlock\x12\x16.dfs.StoreBlockRequest\x1a\x17.dfs.StoreBlockResponse\x12\x46\n\rRetrieveBlock\x12\x19.dfs.RetrieveBlockRequest\x1a\x1a.dfs.RetrieveBlockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=314
  _globals['_ERRORCODE']._serialized_end=368
  _globals['_STOREBLOCKREQUEST']._serialized_start=18
  _globals['_STOREBLOCKREQUEST']._serialized_end=69
  _globals['_STOREBLOCKRESPONSE']._serialized_start=71
  _globals['_STOREBLOCKRESPONSE']._serialized_end=161
  _globals['_RETRIEVEBLOCKREQUEST']._serialized_start=163
  _globals['_RETRIEVEBLOCKREQUEST']._serialized_end=203
  _globals['_RETRIEVEBLOCKRESPONSE']._serialized_start=205
  _globals['_RETRIEVEBLOCKRESPONSE']._serialized_end=312
  _globals['_DATANODE']._serialized_start=371
  _globals['_DATANODE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
